### ISSUE TITLE
mesh label

### ISSUE THREAD

**Issue by www516717402** [AlextheEngineer/Ego3DHand#3]
Hello. Great dataset.
This dataset  whether include mesh label? recently, I want use mesh label to estimate 3D hand.

**Comment by AlextheEngineer** [comment]
Hi, unfortunately the mesh label is not included currently. However, you could generate them by fitting a MANO hand model to the 3D joint locations. Let me know if you have more questions!

________________________________

**Comment by www516717402** [comment]
Thank you for rely.

**Comment by MengHao666** [comment]
> Thank you for rely.

Hi, do you know how to fit a Mano model to get labels?

**Comment by AlextheEngineer** [comment]
In my experiment, I used MANOLayer (https://github.com/hassony2/manopth) and SGD to optimize the MANO pose/shape parameters by minimizing the difference between the canonical 3D joint locations of the MANO hand and the provided ground truth 3D joint locations. The converged result would be a set of MANO parameters that create a hand model that has the same canonical 3D joint locations as the ground truth. You can probably also try to fit it to the global 3D joint locations. Also, you might want to manually constraint the MANO parameters according to the physical constraints of the hand joints (it's not done by default).

**Comment by www516717402** [comment]
> > Thank you for rely.
> 
> Hi, do you know how to fit a Mano model to get labels?

Hello, Solved same as @AlextheEngineer. 
1. Use by inverse kinetics.This method used barely since Very sensitive to noise.
2. Apply SMPL(MANO) modules. Fit pose and shape by 3D root-relate. 
Please see [SMPL](https://smpl.is.tue.mpg.de/), [MANO](https://mano.is.tue.mpg.de/),and other MANO-based paper for details.
