### ISSUE TITLE
camera intrinsic

### ISSUE THREAD

**Issue by zly9844** [AlextheEngineer/Ego3DHand#5]
Did you provide the camera intrinsic in the data set or how can i get the camera intrinsic?

**Comment by AlextheEngineer** [comment]
Hi, I've updated the readme so it includes a section on obtaining the camera intrinsic matrix. Let me know if you have additional questions!

**Comment by zly9844** [comment]
Thank you so much !

**Comment by zly9844** [comment]
I'm sorry to bother you again. But when i build a pointcloud from the depth map of hand using the intrinsic matrix you provided in the readme, the position of the pointcloud is not correct compared with the depth map. I exchanged the px and py in the matrix you provided,  so for the image size (540, 960),  px = 480, py = 270. When i use the changed matrix to build a pointcloud , it looks much better, but still not precisely matched with the depth map. So i want to know if there is something wrong in the intrinsic matrix you provided, or maybe i use the matrix in a wrong way.

**Comment by AlextheEngineer** [comment]
Hi, no worries! You changed px and py, but did you change f in the matrix? Since you are using double the image size comparing to the size ((270, 480)) we provided the sample matrix for, the fx and fy would be 187.932*2 = 375.864. Is this the value you used?

**Comment by zly9844** [comment]
yes, i did. The fx and fy i use is 375.864

**Comment by AlextheEngineer** [comment]
Our coordinates are in order of [row, col, depth], so if you have K = [[fx, 0, px], [0, fy, py], [0, 0, 1]], maybe px should be 270 and py should be 480?

**Comment by zly9844** [comment]
I exchanged the value of px and py. For the image size (540, 960), the px and py should be 270 and 480 using the equation you provide in the readme. but the poitcloud looks not correct, so i use px = 480 and py = 270, it looks much better, but still not precisely matched with the depth map

**Comment by AlextheEngineer** [comment]
How are you generating the point cloud?

**Comment by zly9844** [comment]
z = depth_map / scale
x = (w - px) * z / fx
y = (h - py) * z / fy

**Comment by AlextheEngineer** [comment]
Can you provide an image also that shows what doesn't look right?

**Comment by zly9844** [comment]
The first image is the depth map cropped, the second is the point cloud.



---Original---

**Comment by AlextheEngineer** [comment]
Sorry I'm not seeing the images, maybe you can try emailing me directly "linjiapuzi1994@hotmail.com"

**Comment by AlextheEngineer** [comment]
Closing the issue, potential problem was the use of "z = depth_map / scale", since depth map values are not z values, but the absolute distance from point of interest to the camera origin.
