### ISSUE TITLE
Download speed is slow

### ISSUE THREAD

**Issue by hammer422** [AlextheEngineer/Ego3DHand#7]
Hi, thank you for your great work.
It may be casued by my region, download speed is very slow about 100kb/s [static](https://byu.app.box.com/s/j5a27ilrxraz94ujlvg3gzf715fiq8ih) and [dynamic](https://byu.box.com/s/wtib1zbtmzu9wbwbw1miw8q1oivdbyx6)

Is it possible to download from other links?

Thank you!

**Comment by AlextheEngineer** [comment]
Thanks for your interest, unfortunately I have no other sources to hold the data. The issue might be temporary and has occurred before. If you still cannot download at a normal speed in the next day or two please let me know.

**Comment by hammer422** [comment]
Thank you very much. Finally, I downloaded it through my classmate.
